### PR TITLE
chore: bump dependencies

### PR DESCRIPTION
**Pull request by OsmanAltun**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix
[ ] New feature
[x] Other, please explain:
Bump dependencies

**What changes did you make? (Give an overview)**
 tape 5.2.2  →    5.3.0
 chalk ^4.1.1  →   ^4.1.2
 create-torrent ^4.7.1  →   ^5.0.0
 parse-torrent ^9.1.3  →   ^9.1.4
 yargs ^17.0.1  →  ^17.1.0
 webtorrent ^1.3.2  →   ^1.3.8

### CODE REVIEW

**Comment by DiegoRBaquero** [comment]
These should be done automatically by renovate 🤔

**Comment by OsmanAltun** [comment]
Yeah I know, but it's very slow, I need Yargs 17.1.0 so I thought I might as well do it manually and base my feature branch from this PR.

**Comment by DiegoRBaquero** [comment]
What happens if you reinstall current version? It should pull latest semver ranges

Diego

**Comment by OsmanAltun** [comment]
Since it is a requirement, I made sure it's included in the package file. I get that reinstalling is supposed to pull the latest version because of  the symbol `^17.0.1`

**Comment by DiegoRBaquero** [comment]
This PR won't publish a new version in npm, so that's why I'm wondering. If it works by just reinstalling.

**Pull request closed without merging**
