### PR TITLE
feat: add ability to select specific chromecast devices

### LINKED ISSUE #57: Passing `--chromecast` plays to every chromecast on the network
### Feature proposal

When you pass the `--chromecast` flag, it currently queries and plays to all chromecast on the network.

It would be nice to allow to pass the name of a chromecast device on the network and play to a specific one.

Is this a piece of work that would be welcomed?

### PR DESCRIPTION
**Pull request by alexframe**
This pull request retains existing functionality whilst also extending to allow play to specific chromecast devices. Resolves #57 

Currently the `--chromecast` flag plays to all chromecasts on the network. (This is still the case)

I've added the ability to name which devices to play to. Example usage:

`--chromecast="Living Room TV","Bedroom TV"`

I've tested this locally with multiple chromecasts on my network with success.

Tested in the following LTS versions of node:
- 6.12.3 (Boron)
- 8.9.4 (Carbon)

Please try for yourself and give any feedback necessary to get this merged. Thanks.

### CODE REVIEW

**Comment by iovis9** [comment]
Thanks for this! I don't have any chromecast devices to test this, but looking at the code I'm guessing there's no functionality built around listing the actual devices available, is that right?

I think if we're going to allow to select a device we should also allow to see which devices are visible.

**Comment by alexframe** [comment]
Sure, I can add that. 

How would you like it to work? Just log out all devices when you press enter and have passed the chromecast arg? Or did you have another idea?

Also are we just using console.log?

**Comment by iovis9** [comment]
It's up to you! If you feel like you don't need to get fancy with colors `console.log` will do just fine. Otherwise feel free to use `clivas`.

**Comment by iovis9** [comment]
If you wanna get fancy you can take a look at `inquirer` to let the user choose from a list interactively, but maybe other members of the team don't agree with having another dependency.

**Comment by fabiospampinato** [comment]
> If you wanna get fancy you can take a look at inquirer to let the user choose from a list interactively, but maybe other members of the team don't agree with having another dependency.

IMHO without a way of selecting the target chromecast this feature would be kind of useless.

**Comment by DiegoRBaquero** [comment]
Willing to review and merge if rebased

**Comment by alexframe** [comment]
> Willing to review and merge if rebased

Had a bit of a nightmare with prettier and eslint, but should be fixed and rebased now.

Test 20 is failing, but looks like it fails for me on `master` too.

**Comment by alexframe** [comment]
> Awesome @alexframe , were you able to test this with real devices?

I did in my original PR, but I havne't with the rebase - I can do that after work tonight to confirm it's still working.

**Comment by DiegoRBaquero** [comment]
that'd be great, thank you!

**Comment by gkivanov** [comment]
Any plans on resurrecting this PR?

**Review by feross — APPROVED** [review]

**Comment by feross** [comment]
This PR needs a bit of work before it's ready to land, but I had to dig into the code so thoroughly to understand the changes that I'll just send my fixes in a separate PR.

**Comment by feross** [comment]
See PR here: https://github.com/webtorrent/webtorrent-cli/pull/148

**Comment by feross** [comment]
Released as 3.1.0

**Pull request merged**
