### PR TITLE
Added a `--pip` option for starting the player in PIP mode

### PR DESCRIPTION
**Pull request by fabiospampinato**
it currently only works with IINA

### CODE REVIEW

**Comment by fabiospampinato** [comment]
I'm not sure why all this commits are being listed, maybe I shouldn't have used `rebase`? 🤔 

My only commit is the last one: https://github.com/webtorrent/webtorrent-cli/commit/68f13b7cbc147b9f8ba4959dc290c782de3cb1ed

**Comment by rom1504** [comment]
You can still use rebase (see https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)

**Comment by DiegoRBaquero** [comment]
This needs to updated with the ES6 changes. Wanna do it? And start from master, so not all commits are re added

**Comment by fabiospampinato** [comment]
@DiegoRBaquero Sure, I'll need a few days though, I'm pretty busy right now.

**Comment by fabiospampinato** [comment]
Closing this in favor of https://github.com/webtorrent/webtorrent-cli/pull/85.

**Pull request closed without merging**
